### ISSUE TITLE
[BUG] OpenMM converter not matching exclusions between the default and custom forces

### ISSUE THREAD

**Issue by lohedges** [OpenBioSim/sire#101] opened 2023-08-25 13:35 UTC
The wrapper around the OpenMM `LocalEnergyMinimizer` isn't catching exceptions, so there is no way to know if a minimisation fails. This means that subsequent dynamics might blow up and there is no-way to autominimise, since this will also silently fail. As an example consider [this](https://github.com/OpenBioSim/sire/files/12439601/Methane_Ethane_solv.bss.tar.gz) stream file for a solvated merged methane-ethane system.

First, let's do things with OpenMM directly. Here lambda = 0 works, whereas lambda = 0.4 fails:

```python
In [1]: import BioSimSpace as BSS


In [2]: from openmm import LocalEnergyMinimizer

In [3]: system = BSS.Stream.load("Methane_Ethane_solv.bss")

In [4]: omm = BSS.Convert.toOpenMM(system)

In [5]: omm.set_lambda(0.0)

In [6]: LocalEnergyMinimizer.minimize(omm, maxIterations=100)

In [7]: omm = BSS.Convert.toOpenMM(system)

In [8]: omm.set_lambda(0.4)

In [9]: LocalEnergyMinimizer.minimize(omm, maxIterations=100)
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ in <module>:1                                                                                    │
│                                                                                                  │
│ /home/lester/.conda/envs/openbiosim/lib/python3.10/site-packages/openmm/openmm.py:17208 in       │
│ minimize                                                                                         │
│                                                                                                  │
│   17205 │   │   maxIterations : int                                                              │
│   17206 │   │   │   the maximum number of iterations to perform. If this is 0, minimation is con │
│   17207 │   │   """                                                                              │
│ ❱ 17208 │   │   return _openmm.LocalEnergyMinimizer_minimize(context, tolerance, maxIterations)  │
│   17209 │   __swig_destroy__ = _openmm.delete_LocalEnergyMinimizer                               │
│   17210                                                                                          │
│   17211 # Register LocalEnergyMinimizer in _openmm:                                              │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
OpenMMException: All Forces must have identical exclusions
```

Now let's use the Sire interface:

```python
In [1]: import BioSimSpace as BSS


In [2]: import sire as sr

In [3]: system = BSS.Stream.load("Methane_Ethane_solv.bss")

In [4]: mols = sr.system.System(system._sire_object)

In [5]: m = mols.minimisation(lambda_value=0.0)

In [6]: m.run()
minimisation               0.3 s    3.1 checks / s
Out[6]: Minimisation()

In [7]: m = mols.minimisation(lambda_value=0.4)

In [8]: m.run()
Out[8]: Minimisation()

In [9]: m = mols.minimisation(lambda_value=0.0)

In [10]: m.run()
minimisation               0.3 s    2.9 checks / s
Out[10]: Minimisation()
```

Here the lambda = 0 minimisation runs, whereas the lambda = 0.4 one returns immediately with no exception. (I've run the lambda = 0 one twice to show that it wasn't trying to run on an already minimised system. In which case, I never committed the  changes.)

Looking at the code [here](https://github.com/OpenBioSim/sire/blob/843c7f1edec1935d93c9f168d9280eabc6a7f570/src/sire/mol/_minimisation.py#L52-L57), it appears that the exception is being silently caught (and ignored) in the process of waiting for the run promise to finish. If I replace `spinner.tick()` with `raise`, then I get the same exception as I would when running directly, i.e.:

```python
In [1]: import BioSimSpace as BSS


In [2]: import sire as sr

In [3]: system = BSS.Stream.load("Methane_Ethane_solv.bss")

In [4]: mols = sr.system.System(system._sire_object)

In [5]: m = mols.minimisation(lambda_value=0.4)

In [6]: m.run()
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ in <module>:1                                                                                    │
│                                                                                                  │
│ /home/lester/.conda/envs/openbiosim/lib/python3.10/site-packages/sire/mol/_minimisation.py:98 in │
│ run                                                                                              │
│                                                                                                  │
│    95 │   │   of max_iterations iterations.                                                      │
│    96 │   │   """                                                                                │
│    97 │   │   if not self._d.is_null():                                                          │
│ ❱  98 │   │   │   self._d.run(max_iterations=max_iterations)                                     │
│    99 │   │                                                                                      │
│   100 │   │   return self                                                                        │
│   101                                                                                            │
│                                                                                                  │
│ /home/lester/.conda/envs/openbiosim/lib/python3.10/site-packages/sire/mol/_minimisation.py:39 in │
│ run                                                                                              │
│                                                                                                  │
│    36 │   │   │   │                                                                              │
│    37 │   │   │   │   while not run_promise.done():                                              │
│    38 │   │   │   │   │   try:                                                                   │
│ ❱  39 │   │   │   │   │   │   run_promise.result(timeout=0.2)                                    │
│    40 │   │   │   │   │   except Exception:                                                      │
│    41 │   │   │   │   │   │   raise                                                              │
│    42 │   │   │   │   │   │   spinner.tick()                                                     │
│                                                                                                  │
│ /home/lester/.conda/envs/openbiosim/lib/python3.10/concurrent/futures/_base.py:458 in result     │
│                                                                                                  │
│   455 │   │   │   │   if self._state in [CANCELLED, CANCELLED_AND_NOTIFIED]:                     │
│   456 │   │   │   │   │   raise CancelledError()                                                 │
│   457 │   │   │   │   elif self._state == FINISHED:                                              │
│ ❱ 458 │   │   │   │   │   return self.__get_result()                                             │
│   459 │   │   │   │   else:                                                                      │
│   460 │   │   │   │   │   raise TimeoutError()                                                   │
│   461 │   │   finally:                                                                           │
│                                                                                                  │
│ /home/lester/.conda/envs/openbiosim/lib/python3.10/concurrent/futures/_base.py:403 in            │
│ __get_result                                                                                     │
│                                                                                                  │
│   400 │   def __get_result(self):                                                                │
│   401 │   │   if self._exception:                                                                │
│   402 │   │   │   try:                                                                           │
│ ❱ 403 │   │   │   │   raise self._exception                                                      │
│   404 │   │   │   finally:                                                                       │
│   405 │   │   │   │   # Break a reference cycle with the exception in self._exception            │
│   406 │   │   │   │   self = None                                                                │
│                                                                                                  │
│ /home/lester/.conda/envs/openbiosim/lib/python3.10/concurrent/futures/thread.py:58 in run        │
│                                                                                                  │
│    55 │   │   │   return                                                                         │
│    56 │   │                                                                                      │
│    57 │   │   try:                                                                               │
│ ❱  58 │   │   │   result = self.fn(*self.args, **self.kwargs)                                    │
│    59 │   │   except BaseException as exc:                                                       │
│    60 │   │   │   self.future.set_exception(exc)                                                 │
│    61 │   │   │   # Break a reference cycle with the exception 'exc'                             │
│                                                                                                  │
│ /home/lester/.conda/envs/openbiosim/lib/python3.10/site-packages/sire/mol/_minimisation.py:27 in │
│ runfunc                                                                                          │
│                                                                                                  │
│    24 │   │   from ..base import ProgressBar                                                     │
│    25 │   │                                                                                      │
│    26 │   │   def runfunc(max_its):                                                              │
│ ❱  27 │   │   │   LocalEnergyMinimizer.minimize(                                                 │
│    28 │   │   │   │   self._omm_mols, maxIterations=max_its                                      │
│    29 │   │   │   )                                                                              │
│    30                                                                                            │
│                                                                                                  │
│ /home/lester/.conda/envs/openbiosim/lib/python3.10/site-packages/openmm/openmm.py:17208 in       │
│ minimize                                                                                         │
│                                                                                                  │
│   17205 │   │   maxIterations : int                                                              │
│   17206 │   │   │   the maximum number of iterations to perform. If this is 0, minimation is con │
│   17207 │   │   """                                                                              │
│ ❱ 17208 │   │   return _openmm.LocalEnergyMinimizer_minimize(context, tolerance, maxIterations)  │
│   17209 │   __swig_destroy__ = _openmm.delete_LocalEnergyMinimizer                               │
│   17210                                                                                          │
│   17211 # Register LocalEnergyMinimizer in _openmm:                                              │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
OpenMMException: All Forces must have identical exclusions
```

**Comment by lohedges** [comment] 2023-08-25 14:10
I noticed that the same logic is used in the regular dynamics code, so perhaps we won't catch exceptions there either? I see there is special handling to check the kinetic energy when check-pointing at the end of a block, but I wonder what happens if something else goes wrong, or if there is an error on startup due to some invalid configuration/settings?

**Comment by lohedges** [comment] 2023-08-25 14:29
Regarding the actual exception that was thrown, [this](https://github.com/choderalab/perses/issues/357) is helpful. The error message is somewhat dependent on the chosen platform. For example, if we chose to run using the CPU platform, then the exception is raised _prior_ to the minimisation being run, i.e.:

```python
In [1]: import BioSimSpace as BSS


In [2]: import sire as sr

In [3]: system = BSS.Stream.load("Methane_Ethane_solv.bss")

In [4]: mols = sr.system.System(system._sire_object)

In [5]: m = mols.minimisation(lambda_value=0.4, map={"platform":"cpu"})
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /home/lester/.conda/envs/openbiosim/lib/python3.10/site-packages/sire/legacy/Convert/__init__.py │
│ :330 in sire_to_openmm                                                                           │
│                                                                                                  │
│   327 │   │   try:                                                                               │
│   328 │   │   │   from ._sommcontext import SOMMContext                                          │
│   329 │   │   │                                                                                  │
│ ❱ 330 │   │   │   context = SOMMContext(                                                         │
│   331 │   │   │   │   system=system,                                                             │
│   332 │   │   │   │   integrator=integrator,                                                     │
│   333 │   │   │   │   platform=platform,                                                         │
│                                                                                                  │
│ /home/lester/.conda/envs/openbiosim/lib/python3.10/site-packages/sire/legacy/Convert/_sommcontex │
│ t.py:53 in __init__                                                                              │
│                                                                                                  │
│    50 │   │   │   # the system based on the requested value of lambda                            │
│    51 │   │   │   # There are some things that are unchangeable once                             │
│    52 │   │   │   # the context has been created (e.g. constraints)                              │
│ ❱  53 │   │   │   super().__init__(system, integrator, platform)                                 │
│    54 │   │   │                                                                                  │
│    55 │   │   │   # place the coordinates and velocities into the context                        │
│    56 │   │   │   _set_openmm_coordinates_and_velocities(self, metadata)                         │
│                                                                                                  │
│ /home/lester/.conda/envs/openbiosim/lib/python3.10/site-packages/openmm/openmm.py:3749 in        │
│ __init__                                                                                         │
│                                                                                                  │
│    3746 │   │   properties : map< std::string, std::string >                                     │
│    3747 │   │   │   a set of values for platform-specific properties. Keys are the property name │
│    3748 │   │   """                                                                              │
│ ❱  3749 │   │   _openmm.Context_swiginit(self, _openmm.new_Context(*args))                       │
│    3750 │   │                                                                                    │
│    3751 │   │   self._system = args[0]                                                           │
│    3752 │   │   self._integrator = args[1]                                                       │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
OpenMMException: All Forces must have identical exclusions

During handling of the above exception, another exception occurred:

╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ in <module>:1                                                                                    │
│                                                                                                  │
│ /home/lester/.conda/envs/openbiosim/lib/python3.10/site-packages/sire/system/_system.py:433 in   │
│ minimisation                                                                                     │
│                                                                                                  │
│   430 │   │   """                                                                                │
│   431 │   │   from ..mol import _minimisation                                                    │
│   432 │   │                                                                                      │
│ ❱ 433 │   │   return _minimisation(self, *args, **kwargs)                                        │
│   434 │                                                                                          │
│   435 │   def dynamics(self, *args, **kwargs):                                                   │
│   436 │   │   """                                                                                │
│                                                                                                  │
│ /home/lester/.conda/envs/openbiosim/lib/python3.10/site-packages/sire/mol/__init__.py:1644 in    │
│ _minimisation                                                                                    │
│                                                                                                  │
│   1641 │   if device is not None:                                                                │
│   1642 │   │   map.set("device", str(device))                                                    │
│   1643 │                                                                                         │
│ ❱ 1644 │   return Minimisation(                                                                  │
│   1645 │   │   view,                                                                             │
│   1646 │   │   cutoff=cutoff,                                                                    │
│   1647 │   │   cutoff_type=cutoff_type,                                                          │
│                                                                                                  │
│ /home/lester/.conda/envs/openbiosim/lib/python3.10/site-packages/sire/mol/_minimisation.py:83 in │
│ __init__                                                                                         │
│                                                                                                  │
│    80 │   │                                                                                      │
│    81 │   │   map = create_map(map, extras)                                                      │
│    82 │   │                                                                                      │
│ ❱  83 │   │   self._d = MinimisationData(mols=mols, map=map)                                     │
│    84 │                                                                                          │
│    85 │   def __str__(self):                                                                     │
│    86 │   │   return f"Minimisation()"                                                           │
│                                                                                                  │
│ /home/lester/.conda/envs/openbiosim/lib/python3.10/site-packages/sire/mol/_minimisation.py:15 in │
│ __init__                                                                                         │
│                                                                                                  │
│    12 │   """                                                                                    │
│    13 │                                                                                          │
│    14 │   def __init__(self, mols=None, map=None):                                               │
│ ❱  15 │   │   super().__init__(mols=mols, map=map)                                               │
│    16 │                                                                                          │
│    17 │   def run(self, max_iterations: int):                                                    │
│    18 │   │   from openmm import LocalEnergyMinimizer                                            │
│                                                                                                  │
│ /home/lester/.conda/envs/openbiosim/lib/python3.10/site-packages/sire/mol/_dynamics.py:81 in     │
│ __init__                                                                                         │
│                                                                                                  │
│     78 │   │   │                                                                                 │
│     79 │   │   │   from ..convert import to                                                      │
│     80 │   │   │                                                                                 │
│ ❱   81 │   │   │   self._omm_mols = to(self._sire_mols, "openmm", map=self._map)                 │
│     82 │   │   │   self._omm_state = None                                                        │
│     83 │   │   │   self._omm_state_has_cv = (False, False)                                       │
│     84                                                                                           │
│                                                                                                  │
│ /home/lester/.conda/envs/openbiosim/lib/python3.10/site-packages/sire/convert/__init__.py:74 in  │
│ to                                                                                               │
│                                                                                                  │
│    71 │   elif format == "biosimspace":                                                          │
│    72 │   │   return to_biosimspace(obj, map=map)                                                │
│    73 │   elif format == "openmm":                                                               │
│ ❱  74 │   │   return to_openmm(obj, map=map)                                                     │
│    75 │   else:                                                                                  │
│    76 │   │   raise ValueError(                                                                  │
│    77 │   │   │   f"Cannot convert {obj} as the format '{format}' is "                           │
│                                                                                                  │
│ /home/lester/.conda/envs/openbiosim/lib/python3.10/site-packages/sire/convert/__init__.py:193 in │
│ to_openmm                                                                                        │
│                                                                                                  │
│   190 │   Convert the passed object from its current object format to an                         │
│   191 │   openmm object format.                                                                  │
│   192 │   """                                                                                    │
│ ❱ 193 │   return sire_to_openmm(to_sire(obj, map=map), map=map)                                  │
│   194                                                                                            │
│   195                                                                                            │
│   196 def biosimspace_to_sire(obj, map=None):                                                    │
│                                                                                                  │
│ /home/lester/.conda/envs/openbiosim/lib/python3.10/site-packages/sire/convert/__init__.py:366 in │
│ sire_to_openmm                                                                                   │
│                                                                                                  │
│   363 │                                                                                          │
│   364 │   from ..base import create_map                                                          │
│   365 │                                                                                          │
│ ❱ 366 │   mols = _sire_to_openmm(obj, map=create_map(map))                                       │
│   367 │                                                                                          │
│   368 │   return mols                                                                            │
│   369                                                                                            │
│                                                                                                  │
│ /home/lester/.conda/envs/openbiosim/lib/python3.10/site-packages/sire/legacy/Convert/__init__.py │
│ :338 in sire_to_openmm                                                                           │
│                                                                                                  │
│   335 │   │   │   │   map=map,                                                                   │
│   336 │   │   │   )                                                                              │
│   337 │   │   except Exception as e:                                                             │
│ ❱ 338 │   │   │   raise ValueError(                                                              │
│   339 │   │   │   │   "There was a problem creating the OpenMM context. Perhaps "                │
│   340 │   │   │   │   "the platform was not supported for this system, options "                 │
│   341 │   │   │   │   f"or on this computer? The error message is: {e}"                          │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
ValueError: There was a problem creating the OpenMM context. Perhaps the platform was not supported for this system, options or on this
computer? The error message is: All Forces must have identical exclusions
```

It's a bit annoying that the behaviour is different, since it would be good to catch this immediately, rather than when `minimisation.run()` is called.

**Comment by chryswoods** [comment] 2023-09-03 19:04
Thanks - I've fixed the lost exception in [this commit](https://github.com/OpenBioSim/sire/commit/d0dec6fa912dce1016e7311d4fcae5b97f682aa4).

The exception was lost because I hadn't copied across the way that I capture the exception in `_dynamics.py`. In this script, the exception is returned if something goes wrong, and the code checks for this, and then raises it if it is detected, e.g.

```
        def runfunc(num_steps):
            try:
                integrator = self._omm_mols.getIntegrator()
                integrator.step(num_steps)
                return 0
            except Exception as e:
                return e

...

                            while not run_promise.done():
                                try:
                                    result = run_promise.result(timeout=1.0)
                                except Exception:
                                    pass

                            if result == 0:
                                completed += nrun
                                nrun_till_save -= nrun
                                progress.set_progress(completed)
                                run_promise = None
                            else:
                                # make sure we finish processing the last block
                                if process_promise is not None:
                                    try:
                                        process_promise.result()
                                    except Exception:
                                        pass

                                if completed == 0 and auto_fix_minimise:
                                    raise NeedsMinimiseError()

                                # something went wrong - re-raise the exception
                                raise result
```

I've added this same logic to `_minimisation.py` (well, GitHub Copilot did - I started typing it, and it saw what I was doing and copied in the rest!).

The underlying exception is, as you've found, due to the annoying undocumented requirement to match exclusions between `NonbondedForce` and my two `CustomNonbondedForce` objects. I thought I'd got them all, but something during the perturbation must be setting a parameter to zero. OpenMM eagerly converts interactions that involve zero parameters into exclusions, so I have lots of code that uses near-zero values for those, e.g. https://github.com/OpenBioSim/sire/blob/d0dec6fa912dce1016e7311d4fcae5b97f682aa4/wrapper/Convert/SireOpenMM/sire_to_openmm_system.cpp#L1331

I've reproduced the error locally and will debug this week which interactions are causing the issue. There are lots of ways that this can be fixed. I suspect I may go back to managing all of the exceptions/exclusions manually again, rather than relying on them being automatically set.

**Comment by chryswoods** [comment] 2023-09-03 19:05
(I've renamed the issue as the root cause is the major bug)

**Comment by chryswoods** [comment] 2023-09-05 16:34
I'm happy this is now fixed in `feature_restraint`. I'll associate this issue with the PR for that branch when I make it, so that this issue will get closed automatically.

**Closed** 2023-09-18 19:04 UTC
Labels: bug
