### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by mark-cresset** [OpenBioSim/sire#11] opened 2023-02-21 13:49 UTC
**Describe the bug**
Waterswap calculations will not restart successfully

**To Reproduce**
Run a short (2 or 3 iteration) Waterswap calculation. Restart it from the restart file.

The output you get is:
`Error from WaterswapTask id 10 running on cresset22: 'Process crashed??Command: "/home/mark/.conan/data/Sire/2023.1.2/cresset/stable/package/b66dc3dc3eaad13727f79a27b0d1529ed5020351/bin/sire_python" "--ignore-ipython" "/home/mark/.conan/data/Sire/2023.1.2/cresset/stable/package/b66dc3dc3eaad13727f79a27b0d1529ed5020351/share/Sire/scripts/waterswap.py" "-l" "5KR" "-t" "/tmp/FieldEngine-mark/waterswap_350997_1/Input.prmtop" "-c" "/tmp/FieldEngine-mark/waterswap_350997_1/Input.inpcrd" "-C" "/tmp/FieldEngine-mark/waterswap_350997_1/Config.txt" "-n" "6"??Cwd: /tmp/FieldEngine-mark/waterswap_350997_1??Exit code: 0??Output:??Starting /home/mark/.conan/data/Sire/2023.1.2/cresset/stable/package/b66dc3dc3eaad13727f79a27b0d1529ed5020351/bin/sire_python: number of threads equals 16????Loading configuration information from file /tmp/FieldEngine-mark/waterswap_350997_1/Config.txt????Running a waterswap calculation using files /tmp/FieldEngine-mark/waterswap_350997_1/Input.prmtop and /tmp/FieldEngine-mark/waterswap_350997_1/Input.inpcrd.??The absolute binding free energy of the molecule containing residue 5KR will be calculated.????Number of iterations to perform == 6????Using parameters:??===============??ligand name == 5KR??nmoves == 6??pdb frequency == 1??protein crdfile == /tmp/FieldEngine-mark/waterswap_350997_1/Input.inpcrd??protein topfile == /tmp/FieldEngine-mark/waterswap_350997_1/Input.prmtop??restart frequency == 1??water monitor distance == 7 Å???===============??Loading the restart file took 3121 ms??Number of iterations to perform: 6. Number of iterations completed: 3.??Initialising / loading the free energy files took 0 ms??Performing iteration 4...??Test replicas 1 2??Test replicas 3 4??Test replicas 5 6??Test replicas 7 8??Test replicas 9 10??Test replicas 11 12??Test replicas 13 14??...iteration complete (took 104780 ms)??Analysing iteration 4...??Analysing iteration 4...??Saving PDBs of the system at iteration 4...??Traceback (most recent call last):??  File "/home/mark/.conan/data/Sire/2023.1.2/cresset/stable/package/b66dc3dc3eaad13727f79a27b0d1529ed5020351/share/Sire/scripts/waterswap.py", line 205, in <module>??    WSRC.run(params)??  File "/home/mark/.conan/data/Sire/2023.1.2/cresset/stable/package/b66dc3dc3eaad13727f79a27b0d1529ed5020351/lib/python3.9/site-packages/sire/legacy/Tools/__init__.py", line 175, in inner??    retval = func()??  File "/home/mark/.conan/data/Sire/2023.1.2/cresset/stable/package/b66dc3dc3eaad13727f79a27b0d1529ed5020351/lib/python3.9/site-packages/sire/legacy/Tools/WSRC.py", line 2979, in run??    analyseWSRC(wsrc_system, i, bennetts_freenrgs, fep_freenrgs, ti_freenrgs, bound_freenrgs, free_freenrgs,??  File "/home/mark/.conan/data/Sire/2023.1.2/cresset/stable/package/b66dc3dc3eaad13727f79a27b0d1529ed5020351/lib/python3.9/site-packages/sire/legacy/Tools/WSRC.py", line 2882, in analyseWSRC??    printComponents(res_freenrgs[iteration], FILE)??  File "/home/mark/.conan/data/Sire/2023.1.2/cresset/stable/package/b66dc3dc3eaad13727f79a27b0d1529ed5020351/lib/python3.9/site-packages/sire/legacy/Tools/WSRC.py", line 2765, in printComponents??    print("%s  %s  %s  %s" % (comps.viewAt(i).residue(), \??KeyError: 'SireMol::missing_residue: This view does not contain any residues. (call sire.error.get_last_error_details() for more info)'??'
`
**Expected behavior**
The calculation should restart successfully.

**Input files**
Input files for an example restart are attached.

**(please complete the following information):**
 - OS: Linux (happens repeatably on multiple versions)
 - Version of Python: 3.9.15
 - Version of sire: 2023.1.2
 - I confirm that I have checked this bug still exists in the latest released version of sire: Yes

**Comment by mark-cresset** [comment] 2023-02-21 13:51
[Uploading Waterswap_restart.tar.gz…]()

**Comment by mark-cresset** [comment] 2023-02-21 13:54
[Waterswap_restart.tar.gz](https://github.com/OpenBioSim/sire/files/10794129/Waterswap_restart.tar.gz)

**Comment by chryswoods** [comment] 2023-02-22 17:57
Thanks - I confirm this error locally. I have added a try block around the code that throws the exception, and it looks like all the data is there, it has just lost the residue info. Indeed, if I set `res` to `NONE` in the `except`, then the simulation runs well, and produces lots of free energy component outputs (albeit each residue components is labelled with `NONE` rather than the correct residue name). I'll look deeper into this and will re-find the residue data. The issue's root is that there is no restart file for the residue component free energies, and so it is being initialised with an empty set of components. I suspect it is when this is re-initialised that the residues aren't set, because the waterswap system assumes they already exist (as they do internally).

**Comment by chryswoods** [comment] 2023-02-24 19:53
Do you have the files from the `output` directory created by waterswap? There is more than one restart file needed to restart the simulation. You need the `wsrc_restart.s3` file and the `output/freenrg_components.s3`, `output/freenrg_parts.s3` and `output/freenrgs.s3`. Without these, there is no metadata for the identify of the residue in the free energy components.

I've fixed the crash by setting `res` to `None` in the except. This will now continue a simulation from just a `wsrc_restart.s3` file. But it will be without metadata without the other files from `output`.

What is the use case for restarting the simulations after a short run? There may be a lot of work to deal with any edge cases that will be discovered by running waterswap in this atypical manner. Given it will be retired, is it worth continuing to develop / fix this?

**Comment by nigel-palmer** [comment] 2023-02-28 17:02
Attached are the files from a different Waterswap run. I had to split between 2 tar.gz files due to GitHub file size limit.

When this command is run it fails with the `This view does not contain any residues` error.
```
"/path/to/sire_python" "--ignore-ipython" "/path/to/share/Sire/scripts/waterswap.py" "-l" "HDT" "-t" "Input.prmtop" "-c" "Input.inpcrd" "-C" "Config.txt" "-n" "3004"
```
[Waterswap_restart_2.part2.tar.gz](https://github.com/OpenBioSim/sire/files/10852771/Waterswap_restart_2.part2.tar.gz)
[Waterswap_restart_2.part1.tar.gz](https://github.com/OpenBioSim/sire/files/10852773/Waterswap_restart_2.part1.tar.gz)

Thanks

**Comment by chryswoods** [comment] 2023-03-04 18:15
Thanks - that was really helpful. I was able to cut this down to a more rapid test so that I could work out what was going wrong. It ended up being that the loading of the PartialMolecule objects representing each residue from the residue free energy component files was not correct. The AtomSelection objects loaded up the selected atoms, but failed to update the set of selected residues. This meant that the PartialMolecule did not think it had any residues.

I have now fixed this and added in a test to catch any regressions. This is part of the pull request that is currently building. Lester will review it next week and will merge. We will let you know here once this has been merged and updated dev packages built.

**Closed** 2023-03-06 11:50 UTC
Labels: bug

**Comment by chryswoods** [comment] 2023-03-06 11:52
This has been merged and the dev packages are building [here](https://github.com/OpenBioSim/sire/actions/runs/4343077115). They should be available from our `openbiosim/dev` conda channel by mid afternoon. Please re-open if there are any problems :-)

**Comment by nigel-palmer** [comment] 2023-03-08 09:18
I have built Sire on my system and it has fixed the issue.

Thanks
