### ISSUE TITLE
[BUG] GroTop parser doesn't read water bond and angle terms within #ifdef FLEXIBLE block

### ISSUE THREAD

**Issue by noahharrison64** [OpenBioSim/sire#224] opened 2024-08-08 10:33 UTC
Hey, 

I've been encountering what I believe is a bug with BSS. 

**Describe the bug**
When using BioSimSpace to create a solvated system with a ligand, saving it to disk, reading it back, removing the ligand, and then re-saving the system, the #ifdef statements in the output topology file become concatenated incorrectly. This results in broken simulations. (This is a simplification of the context I actually found the bug in)

To Reproduce

1) Load the files created by the following code:
```py
from pathlib import Path
import BioSimSpace as BSS

methanol = BSS.Parameters.gaff("CO").getMolecule()
solvated = BSS.Solvent.tip3p(molecule=methanol, box=3 * [5 * BSS.Units.Length.nanometer])
solvated_system_files = BSS.IO.saveMolecules('solvated_system', solvated, ['grotop', 'gro87'])

solvated = BSS.IO.readMolecules(solvated_system_files)
search_result = solvated.search("resname LIG").molecules()
mol = [search_result.getResult(idx) for idx in range(len(search_result))]
solvated.removeMolecules(mol)
BSS.IO.saveMolecules('solvated_system_new', solvated, ["grotop", "gro87"])
```
2) Inspect the solvated_system_new.top file.
3) Observe that the #ifdef statements are concatenated incorrectly.

**Expected behavior**
I think that the #ifdef statement in the output topology file should maintain the correct structure after removing the ligand and saving the system again. It should look like this:

```
#ifdef FLEXIBLE
[ bonds ]
;   ai     aj  funct  parameters
     1      2      1  0.09572  502416
     1      3      1  0.09572  502416

[ angles ]
;   ai     aj     ak   funct   parameters
     2      1      3       1   104.52  628.02

#else

[ settles ]
; OW    funct   doh dhh
1       1       0.09572 0.15136

[ exclusions ]
1   2   3
2   1   3
3   1   2

#endif
```
However after removing the ligand and writing to disk, it looks like this. Running simulations without the correctly formatted statement leads to the simulation breaking. 
```
#ifdef FLEXIBLE
#else

[ settles ]
; OW    funct   doh dhh
1       1       0.09572 0.15136

[ exclusions ]
1   2   3
2   1   3
3   1   2

#endif
```

 - OS: [e.g. Linux (Ubuntu 20.04.6 LTS (Focal Fossa)
 - Version of Python: Python 3.12.4
 - Version of BioSimSpace: 2024.2.0
 - I confirm that I have checked this bug still exists in the latest released version of BioSimSpace: yes

**Comment by lohedges** [comment] 2024-08-08 11:09
Indeed, if you manually add `#define FLEXIBLE 1` to the topology file, then it works, e.g.:

```python
import BioSimSpace as BSS

methanol = BSS.Parameters.gaff("CO").getMolecule()
solvated = BSS.Solvent.tip3p(molecule=methanol, box=3 * [5 * BSS.Units.Length.nanometer])

# Print the initial bond and angle terms for a water.
print("Initial bond and angle terms...")
print(solvated[1]._sire_object.property("bond"))
print(solvated[1]._sire_object.property("angle"))

# Save to file.
solvated_system_files = BSS.IO.saveMolecules('solvated_system', solvated, ['grotop', 'gro87'])

# Modify the topology file so that FLEXIBLE is defined.
with open("solvated_system.top", "r+") as f:
    content = f.read()
    f.seek(0, 0)
    f.write("#define FLEXIBLE 1\n" + content)

# Reload.
solvated = BSS.IO.readMolecules(solvated_system_files)

# Print the new bond and angle terms for a water.
print("\nNew bond and angle terms...")
print(solvated[1]._sire_object.property("bond"))
print(solvated[1]._sire_object.property("angle"))

Gives:

```
Initial bond and angle terms...
TwoAtomFunctions( size=2
0:    OW:7-HW1:8   : 600.402 [r - 0.9572]^2
1:    OW:7-HW2:9   : 600.402 [r - 0.9572]^2
)
ThreeAtomFunctions( size=1
0:   HW1:8-OW:7-HW2:9      : 75.0502 [theta - 1.82422]^2
)

New bond and angle terms...
TwoAtomFunctions( size=2
0:    OW:7-HW1:8   : 600.402 [r - 0.9572]^2
1:    OW:7-HW2:9   : 600.402 [r - 0.9572]^2
)
ThreeAtomFunctions( size=1
0:   HW1:8-OW:7-HW2:9      : 75.0502 [theta - 1.82422]^2
)
```

**Comment by lohedges** [comment] 2024-08-08 11:21
Aha, there's an easy solution:

```python
import BioSimSpace as BSS

methanol = BSS.Parameters.gaff("CO").getMolecule()
solvated = BSS.Solvent.tip3p(molecule=methanol, box=3 * [5 * BSS.Units.Length.nanometer])

# Print the initial bond and angle terms for a water.
print("Initial bond and angle terms...")
print(solvated[1]._sire_object.property("bond"))
print(solvated[1]._sire_object.property("angle"))

# Save to file and reload.
solvated_system_files = BSS.IO.saveMolecules('solvated_system', solvated, ['grotop', 'gro87'])
solvated = BSS.IO.readMolecules(solvated_system_files, property_map={"GROMACS_DEFINE": "FLEXIBLE"})

# Print the new bond and angle terms for a water.
print("\nNew bond and angle terms...")
print(solvated[1]._sire_object.property("bond"))
print(solvated[1]._sire_object.property("angle"))
```

The key bit being:

```
solvated = BSS.IO.readMolecules(solvated_system_files, property_map={"GROMACS_DEFINE": "FLEXIBLE"})
```

Which gives:

```
Initial bond and angle terms...
TwoAtomFunctions( size=2
0:    OW:7-HW1:8   : 600.402 [r - 0.9572]^2
1:    OW:7-HW2:9   : 600.402 [r - 0.9572]^2
)
ThreeAtomFunctions( size=1
0:   HW1:8-OW:7-HW2:9      : 75.0502 [theta - 1.82422]^2
)

New bond and angle terms...
TwoAtomFunctions( size=2
0:    OW:7-HW1:8   : 600.402 [r - 0.9572]^2
1:    OW:7-HW2:9   : 600.402 [r - 0.9572]^2
)
ThreeAtomFunctions( size=1
0:   HW1:8-OW:7-HW2:9      : 75.0502 [theta - 1.82422]^2
)
```

I'll just update the BioSImSpace `readMolecules` function to always add this to the map so that we ensure that the bonded terms are present for water molecules.

**Comment by noahharrison64** [comment] 2024-08-08 12:52
Hey @lohedges,

Thanks for digging into this. Your suggestion of using the property_map appears to work perfectly. Hope it's been useful having the bug brought to your attention - I'll keep an eye out for an updated BSS with a bug fix but will use the workaround in the meantime.

Noah

**Comment by lohedges** [comment] 2024-08-08 12:57
No problem. I don't think that it's actually a bug if you consider the specification of the topology file, i.e.  you should only parse what has been included via `#define`. The issue is that it's not obvious to the user how to fix this. I think it might be better for me to add an extra kwarg to `readMolecules` called `gromacs_defines` that can take a list of values, then inject these into the property map automatically. While this requires user input, it means that we don't automatically do something behind their back, which might not be what they want. It would also be clearly documented in the API docs and I can provide an example too.

Cheers.

**Comment by lohedges** [comment] 2024-08-08 13:43
Closing since this is expected behaviour, just not obvious to the user.

**Closed by lohedges** 2024-08-08 13:43 UTC
Labels: bug

**Comment by noahharrison64** [comment] 2024-08-08 14:24
Sounds good, thanks.
