### ISSUE TITLE
[BUG] BSS fails to add ligand resname to PDB when saving non-cognate system 

### ISSUE THREAD

**Issue by noahharrison64** [OpenBioSim/sire#141] opened 2024-01-12 16:47 UTC
Hi, me again...

I've just encountered a semi-bug with BSS. I say semi-bug because I'm working with a "non-cognate" system, meaning I'm making some modifications to the natively generated BSS topologies so I can work with an external program (PMX) to create hybrid topologies that I can read back in as BSS perturbable systems. I followed a similar process to that detailed in this github [issue](https://github.com/michellab/BioSimSpace/issues/234). 

It appears adding the hybrid topologies to the protein, and then writing the system to disk leads to the loss of the hybrid molecule residue name. However this is only the case for writing to pdb and not to gro87. The pdb files can't be used in gromacs simulations (two grommp errors relating to the periodic box vectors), but the gro files work fine.

I have attached the input files. I'm aware that since I'm using my own topologies as input it's likely I'm encountering a rare bug, and it may be because I've overlooked something in the code used to generate these topologies. I thought it was worth bringing up here though. 

**To Reproduce**
```py
from pathlib import Path
import BioSimSpace as BSS

input_dir = Path('input_files')
ligand_files = [str(input_dir / f"lig-47_lig-65_merged{i}.{file_format}") for i in [0, 1] for file_format in ['prm7', 'rst7']]
protein_files = list([str(f) for f in input_dir.glob('protein*')])


merged_mol = BSS.IO.readPerturbableSystem(*ligand_files)
protein = BSS.IO.readMolecules(protein_files)
protein.addMolecules(merged_mol)
BSS.IO.saveMolecules('system', protein, ['pdb', 'gro87', 'grotop'])
```

**Input files**

[input_files.zip](https://github.com/OpenBioSim/biosimspace/files/13921662/input_files.zip)

**(please complete the following information):**
 - OS: Linux
 - Version of Python: 3.11.6  (I was surprised to see this python version when I checked this now, since I've always installed BSS conda env / dependencies via docs install guide which says BSS is only package for 3.8 and 3.9. Not sure how long I've been running BSS on this python version) 
 - Version of BioSimSpace: 2023.5.0
 - I confirm that I have checked this bug still exists in the latest released version of BioSimSpace: yes

**Comment by chryswoods** [comment] 2024-01-12 17:52
Thanks for getting in touch - I've transferred this to the sire repo because I think this is a bug in sire.

Thanks for taking the time to make such a good bug report. I would definitely class this as a bug. We aim to make sure that the file parsers are symmetric, i.e. they can write back the same information that they read. The PDB parser losing the residue name does sound like it breaks that goal. I'll take a look over over the next few days to reproduce it and hopefully come up with a fix :-)

**Comment by lohedges** [comment] 2024-01-12 17:59
That's very strange. I can see that the residue name is set correctly in the molecule, e.g.:

```python
In [1]: for res in protein[1].getResidues():
    ...:     print(res)
    ...:
<BioSimSpace.Residue: name='MOL', molecule=2, index=0, nAtoms=53>
```

However, as you've found, it isn't being written to PDB. All residue names for the first molecule are written just fine. I'll try to debug what's going wrong. It's quite puzzling since the logic for extracting the residue name is very simple and I can't think why it would be different for these two molecules. I find the same thing happens if I just write molecule index 1 to file, so it isn't something special about having both molecules in the system.

**Comment by lohedges** [comment] 2024-01-12 18:17
Yes, that's exactly it. We skip generating a PDBAtom object if there isn't a `coordinates` property, which isn't the case here since it is perturbable. To write a given end state you'd need to do, e.g. for the lambda = 0 state.

```python
from pathlib import Path
import BioSimSpace as BSS

input_dir = Path('input_files')
ligand_files = [str(input_dir / f"lig-47_lig-65_merged{i}.{file_format}") for i in [0, 1] for file_format in ['prm7', 'rst7']]
protein_files = list([str(f) for f in input_dir.glob('protein*')])


merged_mol = BSS.IO.readPerturbableSystem(*ligand_files)
protein = BSS.IO.readMolecules(protein_files)
protein.addMolecules(merged_mol[0]._toRegularMolecule(is_lambda1=False))
BSS.IO.saveMolecules('system', protein, ['pdb', 'gro87', 'grotop'])
```

The key bit here is extracting the lambda = 0 state of the merged topology as follows:

```python
protein.addMolecules(merged_mol[0]._toRegularMolecule(is_lambda1=False))
```

The PDB file then contains the merged molecule for the lambda = 0 state:

```
tail system.pdb
ATOM     46  HV  MOL     1      65.323 -30.947  31.181  1.00  0.00          XX
ATOM     47  HV  MOL     1      64.434 -32.305  31.880  1.00  0.00          XX
ATOM     48  HV  MOL     1      63.601 -30.785  31.531  1.00  0.00          XX
ATOM     49  DCL MOL     1      61.668 -32.908  30.825  1.00  0.00          XX
ATOM     50  DC  MOL     1      61.182 -33.838  27.948  1.00  0.00          XX
ATOM     51  HV  MOL     1      61.135 -34.142  26.905  1.00  0.00          XX
ATOM     52  HV  MOL     1      61.116 -34.734  28.567  1.00  0.00          XX
ATOM     53  HV  MOL     1      60.323 -33.205  28.158  1.00  0.00          XX
ENDMDL
END
```

It works for GROMACS format since the parser is able to handle the merged topology, as this is needed for setting up FEP simulations. (PDB isn't typically used for this.)

**Comment by lohedges** [comment] 2024-01-12 18:19
The clue was that your original PDB contained null coordinates, i.e.:

```
tail system.pdb
ATOM     46  HV        446       0.000   0.000   0.000  1.00  0.00           X
ATOM     47  HV        446       0.000   0.000   0.000  1.00  0.00           X
ATOM     48  HV        446       0.000   0.000   0.000  1.00  0.00           X
ATOM     49  DCL       446       0.000   0.000   0.000  1.00  0.00           X
ATOM     50  DC        446       0.000   0.000   0.000  1.00  0.00           X
ATOM     51  HV        446       0.000   0.000   0.000  1.00  0.00           X
ATOM     52  HV        446       0.000   0.000   0.000  1.00  0.00           X
ATOM     53  HV        446       0.000   0.000   0.000  1.00  0.00           X
ENDMDL
END
```

I still think we should re-order the logic in the PDB2 parser since it makes sense to retain the info that we do have, i.e. that which is unaffected by an incorrect atom mapping, such as the residue name, number, etc.

**Closed** 2024-01-15 11:07 UTC
Labels: bug
